export const IMAGES = {
  // Signature brand hero image (Model in champagne silk robe on bouclé sofa)
  heroModel: '/images/hero-model.jpg',
  robe: '/images/robe.jpg',

  // User uploaded authentic photos
  albaBluReal: '/images/alba-blu-real.jpg',
  polkaSlip: '/images/polka-slip.jpg',
  maternidadePink: '/images/maternidade-pink.jpg',
  slipFirenze: '/images/slip-firenze.webp',
  butterflyPajama: '/images/butterfly-pajama.webp',
  fuchsiaLace: '/images/fuchsia-lace.webp',
  nestiDanteSoaps: '/images/nesti-dante-soaps.webp',

  // Curated luxury editorial candles & fragrances
  candleLuxury: '/images/candle-luxury.jpg',
  candleFico: '/images/candle-fico.jpg',
  diffuserToscana: '/images/diffuser-toscana.jpg',
  perfumeGold: '/images/perfume-gold.jpg',
  ritualBath: '/images/ritual-bath.jpg',

  // Complementary original brand assets
  couple: '/images/couple.jpg',
  respira: '/images/respira.jpg',
  editorial1: '/images/editorial1.jpg',
  pinkbra: '/images/pinkbra.jpg',
  mens: '/images/mens.jpg',
  candle: '/images/candle.jpg',
  editorial2: '/images/editorial2.jpg',
  hearts: '/images/hearts.jpg',
  bluelace: '/images/bluelace.jpg',
  silk: '/images/silk.jpg',
  satin: '/images/satin.jpg',
  lace: '/images/lace.jpg',
  fig: '/images/fig.jpg',
  amber: '/images/amber.jpg',
  diffuser: '/images/diffuser.jpg',
  no1: '/images/no1.jpg',
  rose: '/images/rose.jpg',
  gift: '/images/gift.jpg',
  luxurygold: '/images/luxurygold.jpg',
  logo: '/images/logo.png',
};

export const CATEGORIES = [
  {
    slug: 'pijamas',
    name: 'Pijamas Premium',
    description: 'Seda, cetim, renda e estampas autorais para os seus rituais de descanso.',
    image: IMAGES.heroModel,
    number: '01',
  },
  {
    slug: 'velas',
    name: 'Velas & Ritual',
    description: 'Ceras vegetais e fragrâncias italianas que transformam o ambiente.',
    image: IMAGES.candleLuxury,
    number: '02',
  },
  {
    slug: 'perfumaria',
    name: 'Perfumaria Italiana',
    description: 'Eau de Parfum e sabonetes importados para presentear a si.',
    image: IMAGES.perfumeGold,
    number: '03',
  },
];

export const MOODS = [
  'Noite de Seda',
  'Manhãs Silenciosas',
  'Ritual de Banho',
  'Meia-Noite',
  'Presente',
];

export const PRODUCTS = [
  {
    id: 'respira',
    name: 'Conjunto Respira',
    price: 379,
    category: 'pijamas',
    mood: 'Manhãs Silenciosas',
    moods: ['Manhãs Silenciosas', 'Presente'],
    featured: true,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: 'Tecido Fluity · 87% poliamida 13% elastano',
    description: 'Conjunto de manga longa e calça com estampa de folhagem tropical. Tecido Fluity leve, fresco e de caimento fluido — do P ao GG.',
    images: [IMAGES.respira, IMAGES.couple],
  },
  {
    id: 'alba-blu',
    name: 'Camisola Alba Blu',
    price: 429,
    category: 'pijamas',
    mood: 'Noite de Seda',
    moods: ['Noite de Seda', 'Manhãs Silenciosas'],
    featured: true,
    sizes: ['P', 'M', 'G'],
    composition: 'Viscose nobre com renda francesa',
    description: 'Camisola azul-petróleo com renda delicada no decote e mangas, acompanhada de robe no mesmo tom. Para manhãs de luz suave.',
    images: [IMAGES.albaBluReal, IMAGES.bluelace],
  },
  {
    id: 'firenze',
    name: 'Camisola Slip Firenze',
    price: 429,
    category: 'pijamas',
    mood: 'Noite de Seda',
    moods: ['Noite de Seda', 'Meia-Noite'],
    featured: true,
    sizes: ['P', 'M', 'G'],
    composition: 'Cetim de seda fluido com decote degagê',
    description: 'Camisola slip longa em seda marmorizada verde-água, decote degagê fluido e costas com caimento impecável. Uma peça para sonhar acordada.',
    images: [IMAGES.slipFirenze, IMAGES.heroModel],
  },
  {
    id: 'farfalla',
    name: 'Conjunto Farfalla Blu',
    price: 369,
    category: 'pijamas',
    mood: 'Manhãs Silenciosas',
    moods: ['Manhãs Silenciosas', 'Presente'],
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: 'Seda toque de cetim com estampa botânica',
    description: 'Camisa manga curta e shorts em azul-celeste com estampa suave de borboletas rosas em aquarela. Toque sedoso e modelagem relaxada.',
    images: [IMAGES.butterflyPajama],
  },
  {
    id: 'fuchsia-lace',
    name: 'Conjunto Seda Magenta',
    price: 299,
    category: 'pijamas',
    mood: 'Noite de Seda',
    moods: ['Noite de Seda', 'Meia-Noite'],
    featured: false,
    sizes: ['P', 'M', 'G'],
    composition: 'Cetim de seda com aplicação de renda chantilly',
    description: 'Regata com decote V e shorts com barra trabalhada em renda nobre na cor magenta vibrante. O encontro da cor com a sofisticação da seda.',
    images: [IMAGES.fuchsiaLace],
  },
  {
    id: 'cuore',
    name: 'Camisola Cuore',
    price: 349,
    category: 'pijamas',
    mood: 'Manhãs Silenciosas',
    moods: ['Manhãs Silenciosas', 'Presente'],
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: 'Algodão pima com estampa de corações',
    description: 'Camisola branca estampada com corações vermelhos desenhados à mão. Leve, romântica e perfeita para presentear.',
    images: [IMAGES.hearts],
  },
  {
    id: 'sabbia-uomo',
    name: 'Pijama Sabbia Uomo',
    price: 329,
    category: 'pijamas',
    mood: 'Presente',
    moods: ['Presente', 'Manhãs Silenciosas'],
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: 'Algodão pima peruano',
    description: 'Conjunto masculino de camiseta branca e shorts cor ferrugem. O caimento do algodão pima que vira ritual de casa.',
    images: [IMAGES.mens, IMAGES.couple],
  },
  {
    id: 'seam-rosa',
    name: 'Top Seamless Rosa',
    price: 189,
    category: 'pijamas',
    mood: 'Noite de Seda',
    moods: ['Noite de Seda', 'Manhãs Silenciosas'],
    featured: false,
    sizes: ['P', 'M', 'G'],
    composition: 'Modal sem costura com recortes a laser',
    description: 'Top sem costura em rosa-pálido, com recortes pinhole a laser na faixa inferior. Segunda pele para dormir ou ficar.',
    images: [IMAGES.pinkbra],
  },
  {
    id: 'notte',
    name: 'Pijama de Seda Notte',
    price: 689,
    category: 'pijamas',
    mood: 'Noite de Seda',
    moods: ['Noite de Seda', 'Meia-Noite', 'Presente'],
    featured: true,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: '100% seda pura com acabamento em viés',
    description: 'Conjunto de camisa e calça em seda pura, caimento fluido e acabamento em viés. Para noites que pedem delicadeza e luxo silencioso.',
    images: [IMAGES.heroModel, IMAGES.silk, IMAGES.satin],
  },
  {
    id: 'sabbia-robe',
    name: 'Robe de Cetim Sabbia',
    price: 619,
    category: 'pijamas',
    mood: 'Manhãs Silenciosas',
    moods: ['Manhãs Silenciosas', 'Noite de Seda', 'Presente'],
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: 'Cetim com forro leve e faixa',
    description: 'Robe longo em tom areia champanhe, com faixa de amarração, punhos de renda francesa e bolsos embutidos.',
    images: [IMAGES.heroModel, IMAGES.robe],
  },
  {
    id: 'romantica',
    name: 'Vela Nesti Dante Romantica',
    price: 209,
    category: 'velas',
    mood: 'Ritual de Banho',
    moods: ['Ritual de Banho', 'Noite de Seda', 'Presente'],
    featured: true,
    sizes: ['Único'],
    composition: 'Cera vegetal · 250g · 50h de queima',
    notes: ['Rosa', 'Peônia', 'Almíscar branco'],
    description: 'Vela italiana da linha Romantica, com cera vegetal e fragrância floral nobre de rosa toscana e peônia.',
    images: [IMAGES.candleLuxury, IMAGES.nestiDanteSoaps],
  },
  {
    id: 'fico',
    name: "Vela Fico d'Italia",
    price: 189,
    category: 'velas',
    mood: 'Ritual de Banho',
    moods: ['Ritual de Banho', 'Manhãs Silenciosas', 'Presente'],
    featured: false,
    sizes: ['Único'],
    composition: 'Cera vegetal · 220g · 45h de queima',
    notes: ['Figo', 'Folhas verdes', 'Cedro'],
    description: "Cera vegetal com pavio de algodão puro e fragrância autêntica de figo mediterrâneo, folhas verdes e madeira clara toscana.",
    images: [IMAGES.candleFico, IMAGES.candleLuxury],
  },
  {
    id: 'sabbia-vela',
    name: "Vela Sabbia d'Oro",
    price: 165,
    category: 'velas',
    mood: 'Manhãs Silenciosas',
    moods: ['Manhãs Silenciosas', 'Meia-Noite', 'Noite de Seda'],
    featured: false,
    sizes: ['Único'],
    composition: 'Cera vegetal · 180g · 38h de queima',
    notes: ['Âmbar', 'Baunilha', 'Sândalo'],
    description: 'Fragrância âmbar e baunilha em recipiente de vidro âmbar artesanal, perfeita para acender nas primeiras horas do dia.',
    images: [IMAGES.candleLuxury],
  },
  {
    id: 'toscana',
    name: 'Difusor Toscana',
    price: 219,
    category: 'velas',
    mood: 'Ritual de Banho',
    moods: ['Ritual de Banho', 'Manhãs Silenciosas', 'Presente'],
    featured: false,
    sizes: ['Único'],
    composition: '250ml · varetas de fibra natural · dura até 3 meses',
    notes: ['Bergamota', 'Alecrim', 'Almíscar branco'],
    description: 'Difusor de varetas com essência botânica italiana de ervas mediterrâneas, bergamota fresca e madeiras nobres.',
    images: [IMAGES.diffuserToscana, IMAGES.no1],
  },
  {
    id: 'luxury-gold',
    name: 'Eau de Parfum Luxury Gold',
    price: 529,
    category: 'perfumaria',
    mood: 'Meia-Noite',
    moods: ['Meia-Noite', 'Noite de Seda', 'Presente'],
    featured: true,
    sizes: ['50ml'],
    composition: 'Eau de Parfum · 50ml · Firenze',
    notes: ['Bergamota', 'Ylang-ylang', 'Âmbar e oud'],
    description: 'Profumo italiano Luxury Gold: abertura cítrica, coração floral de ylang-ylang e fundo amadeirado de oud e âmbar. A sofisticação em frasco dourado lapidado.',
    images: [IMAGES.perfumeGold],
  },
  {
    id: 'celli-no1',
    name: 'Eau de Parfum Célli Nº1',
    price: 459,
    category: 'perfumaria',
    mood: 'Meia-Noite',
    moods: ['Meia-Noite', 'Noite de Seda', 'Manhãs Silenciosas'],
    featured: false,
    sizes: ['50ml'],
    composition: 'Eau de Parfum · 50ml',
    notes: ['Bergamota', 'Jasmim', 'Âmbar e cedro'],
    description: 'A assinatura da casa: cítrico de abertura, coração floral nobre e fundo amadeirado quente.',
    images: [IMAGES.no1, IMAGES.perfumeGold],
  },
  {
    id: 'rosa',
    name: 'Eau de Parfum Rosa Antica',
    price: 389,
    category: 'perfumaria',
    mood: 'Meia-Noite',
    moods: ['Meia-Noite', 'Noite de Seda', 'Presente'],
    featured: false,
    sizes: ['50ml'],
    composition: 'Eau de Parfum · 50ml',
    notes: ['Pimenta rosa', 'Rosa damascena', 'Almíscar'],
    description: 'Rosa damascena sobre pimenta rosa e almíscar. Intenso, feminino e memorável.',
    images: [IMAGES.perfumeGold],
  },
  {
    id: 'sabonete',
    name: 'Sabonetes Nesti Dante Villa Sole',
    price: 119,
    category: 'perfumaria',
    mood: 'Ritual de Banho',
    moods: ['Ritual de Banho', 'Presente', 'Manhãs Silenciosas'],
    featured: true,
    sizes: ['500ml'],
    composition: 'Sapone Liquido Vegetale · 500ml · Made in Firenze',
    notes: ['Fresia Blu delle Eolie', 'Ervas Mediterrâneas'],
    description: 'Autêntico sabonete líquido vegetal italiano Nesti Dante Firenze, frasco decorado em maiólica azul e notas frescas de frésia azul.',
    images: [IMAGES.nestiDanteSoaps],
  },
  {
    id: 'kit',
    name: 'Kit Presente Maison',
    price: 790,
    category: 'perfumaria',
    mood: 'Presente',
    moods: ['Presente', 'Ritual de Banho', 'Meia-Noite'],
    featured: true,
    sizes: ['Único'],
    composition: '3 peças · caixa rígida forrada',
    description: 'Perfume Célli Nº1, vela artesanal botânica e sabonete italiano em embalagem de presente com laço de cetim.',
    images: [IMAGES.gift, IMAGES.perfumeGold],
  },
];

export const PILLARS = [
  {
    number: '01',
    title: 'Curadoria italiana',
    description: 'Perfumaria importada e tecidos escolhidos peça por peça, direto dos ateliês.',
  },
  {
    number: '02',
    title: 'Embalagem de presente',
    description: 'Toda compra chega pronta para presentear, com laço e cartão escrito à mão.',
  },
  {
    number: '03',
    title: 'Atendimento pessoal',
    description: 'Você fala com a gente pelo WhatsApp e monta o pedido com calma, sem carrinho frio.',
  },
];

export const LOOKBOOK_IMAGES = [
  IMAGES.heroModel,
  IMAGES.albaBluReal,
  IMAGES.slipFirenze,
  IMAGES.butterflyPajama,
  IMAGES.fuchsiaLace,
  IMAGES.polkaSlip,
  IMAGES.maternidadePink,
  IMAGES.candleLuxury,
  IMAGES.perfumeGold,
  IMAGES.nestiDanteSoaps,
  IMAGES.candleFico,
  IMAGES.diffuserToscana,
  IMAGES.ritualBath,
  IMAGES.respira,
  IMAGES.hearts,
];

export const GIFT_THRESHOLD = 790;
export const WHATSAPP_PHONE = '5519994727551';

export const formatPrice = (value) => {
  return value.toLocaleString('pt-BR', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
};

export const getWhatsAppLink = (message) => {
  return `https://wa.me/${WHATSAPP_PHONE}?text=${encodeURIComponent(message)}`;
};
