export const IMAGES = {
  heroDesktop: '/images/hero-desktop.jpg',
  heroMobile: '/images/robe.jpg',
  robe: '/images/robe.jpg',
  couple: '/images/couple.jpg',
  respira: '/images/respira.jpg',
  editorial1: '/images/editorial1.jpg',
  pinkbra: '/images/pinkbra.jpg',
  mens: '/images/mens.jpg',
  candle: '/images/candle.jpg',
  editorial2: '/images/editorial2.jpg',
  hearts: '/images/hearts.jpg',
  bluelace: '/images/bluelace.jpg',
  silk: '/images/silk.jpg',
  satin: '/images/satin.jpg',
  lace: '/images/lace.jpg',
  fig: '/images/fig.jpg',
  amber: '/images/amber.jpg',
  diffuser: '/images/diffuser.jpg',
  no1: '/images/no1.jpg',
  rose: '/images/rose.jpg',
  gift: '/images/gift.jpg',
  luxurygold: '/images/luxurygold.jpg',
  logo: '/images/logo.png',
};

export const CATEGORIES = [
  {
    slug: 'pijamas',
    name: 'Pijamas Premium',
    description: 'Seda, cetim, renda e estampas autorais para os seus rituais de descanso.',
    image: IMAGES.respira,
    number: '01',
  },
  {
    slug: 'velas',
    name: 'Velas & Ritual',
    description: 'Ceras vegetais e fragrâncias italianas que transformam o ambiente.',
    image: IMAGES.candle,
    number: '02',
  },
  {
    slug: 'perfumaria',
    name: 'Perfumaria Italiana',
    description: 'Eau de Parfum e sabonetes importados para presentear a si.',
    image: IMAGES.luxurygold,
    number: '03',
  },
];

export const MOODS = [
  'Noite de Seda',
  'Manhãs Silenciosas',
  'Ritual de Banho',
  'Meia-Noite',
  'Presente',
];

export const PRODUCTS = [
  {
    id: 'respira',
    name: 'Conjunto Respira',
    price: 379,
    category: 'pijamas',
    mood: 'Manhãs Silenciosas',
    featured: true,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: 'Tecido Fluity · 87% poliamida 13% elastano',
    description: 'Conjunto de manga longa e calça com estampa de folhagem tropical. Tecido Fluity leve, fresco e de caimento fluido — do P ao GG.',
    images: [IMAGES.respira, IMAGES.couple],
  },
  {
    id: 'alba-blu',
    name: 'Camisola Alba Blu',
    price: 429,
    category: 'pijamas',
    mood: 'Noite de Seda',
    featured: true,
    sizes: ['P', 'M', 'G'],
    composition: 'Viscose com renda francesa',
    description: 'Camisola azul-petróleo com renda no decote e nas mangas, acompanhada de robe de amarração no mesmo tom. Para manhãs de luz suave.',
    images: [IMAGES.bluelace],
  },
  {
    id: 'cuore',
    name: 'Camisola Cuore',
    price: 349,
    category: 'pijamas',
    mood: 'Manhãs Silenciosas',
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: 'Algodão pima com estampa de corações',
    description: 'Camisola branca estampada com corações vermelhos desenhados à mão. Leve, romântica e perfeita para presentear.',
    images: [IMAGES.hearts],
  },
  {
    id: 'sabbia-uomo',
    name: 'Pijama Sabbia Uomo',
    price: 329,
    category: 'pijamas',
    mood: 'Presente',
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: 'Algodão pima',
    description: 'Conjunto masculino de camiseta branca e shorts cor ferrugem. O caimento do algodão pima que vira ritual de casa.',
    images: [IMAGES.mens, IMAGES.couple],
  },
  {
    id: 'seam-rosa',
    name: 'Top Seamless Rosa',
    price: 189,
    category: 'pijamas',
    mood: 'Noite de Seda',
    featured: false,
    sizes: ['P', 'M', 'G'],
    composition: 'Modal sem costura com recortes a laser',
    description: 'Top sem costura em rosa-pálido, com recortes pinhole a laser na faixa inferior. Segunda pele para dormir ou ficar.',
    images: [IMAGES.pinkbra],
  },
  {
    id: 'notte',
    name: 'Pijama de Seda Notte',
    price: 689,
    category: 'pijamas',
    mood: 'Noite de Seda',
    featured: true,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: '100% seda com acabamento em viés',
    description: 'Conjunto de camisa e calça em seda pura, caimento fluido e acabamento em viés. Para noites que pedem delicadeza.',
    images: [IMAGES.silk, IMAGES.satin],
  },
  {
    id: 'firenze',
    name: 'Camisola de Renda Firenze',
    price: 429,
    category: 'pijamas',
    mood: 'Noite de Seda',
    featured: false,
    sizes: ['P', 'M', 'G'],
    composition: 'Cetim com aplicação de renda',
    description: 'Camisola longa com detalhe de renda francesa no decote e nas laterais.',
    images: [IMAGES.lace],
  },
  {
    id: 'sabbia-robe',
    name: 'Robe de Cetim Sabbia',
    price: 619,
    category: 'pijamas',
    mood: 'Manhãs Silenciosas',
    featured: false,
    sizes: ['P', 'M', 'G', 'GG'],
    composition: 'Cetim com forro leve',
    description: 'Robe longo em tom areia, com faixa de amarração e bolsos embutidos.',
    images: [IMAGES.robe],
  },
  {
    id: 'romantica',
    name: 'Vela Nesti Dante Romantica',
    price: 209,
    category: 'velas',
    mood: 'Ritual de Banho',
    featured: true,
    sizes: ['Único'],
    composition: 'Cera vegetal · 250g · 50h de queima',
    notes: ['Rosa', 'Peônia', 'Almíscar branco'],
    description: 'Vela italiana da linha Romantica, com fragrância floral de rosa e peônia. Acompanha sabonetes Chic Animalier e Immunity no ritual.',
    images: [IMAGES.candle],
  },
  {
    id: 'fico',
    name: "Vela Fico d'Italia",
    price: 189,
    category: 'velas',
    mood: 'Ritual de Banho',
    featured: false,
    sizes: ['Único'],
    composition: 'Cera vegetal · 220g · 45h de queima',
    notes: ['Figo', 'Folhas verdes', 'Cedro'],
    description: "Cera vegetal com pavio de algodão e fragrância de figo fresco, folhas verdes e madeira clara.",
    images: [IMAGES.fig, IMAGES.amber],
  },
  {
    id: 'sabbia-vela',
    name: "Vela Sabbia d'Oro",
    price: 165,
    category: 'velas',
    mood: 'Manhãs Silenciosas',
    featured: false,
    sizes: ['Único'],
    composition: 'Cera vegetal · 180g · 38h de queima',
    notes: ['Âmbar', 'Baunilha', 'Sândalo'],
    description: 'Fragrância âmbar e baunilha em recipiente de vidro âmbar, para reutilizar depois.',
    images: [IMAGES.amber],
  },
  {
    id: 'toscana',
    name: 'Difusor Toscana',
    price: 219,
    category: 'velas',
    mood: 'Ritual de Banho',
    featured: false,
    sizes: ['Único'],
    composition: '250ml · dura até 3 meses',
    notes: ['Bergamota', 'Alecrim', 'Almíscar branco'],
    description: 'Difusor de varetas com fragrância de ervas mediterrâneas e bergamota.',
    images: [IMAGES.diffuser],
  },
  {
    id: 'luxury-gold',
    name: 'Eau de Parfum Luxury Gold',
    price: 529,
    category: 'perfumaria',
    mood: 'Meia-Noite',
    featured: true,
    sizes: ['50ml'],
    composition: 'Eau de Parfum · 50ml · Nesti Dante',
    notes: ['Bergamota', 'Ylang-ylang', 'Âmbar e oud'],
    description: 'Profumo italiano Luxury Gold: abertura cítrica, coração floral de ylang-ylang e fundo amadeirado de oud e âmbar. A sofisticação em frasco dourado.',
    images: [IMAGES.luxurygold],
  },
  {
    id: 'celli-no1',
    name: 'Eau de Parfum Célli Nº1',
    price: 459,
    category: 'perfumaria',
    mood: 'Meia-Noite',
    featured: false,
    sizes: ['50ml'],
    composition: 'Eau de Parfum · 50ml',
    notes: ['Bergamota', 'Jasmim', 'Âmbar e cedro'],
    description: 'A assinatura da casa: cítrico de abertura, coração floral e fundo amadeirado quente.',
    images: [IMAGES.no1, IMAGES.rose],
  },
  {
    id: 'rosa',
    name: 'Eau de Parfum Rosa Antica',
    price: 389,
    category: 'perfumaria',
    mood: 'Meia-Noite',
    featured: false,
    sizes: ['50ml'],
    composition: 'Eau de Parfum · 50ml',
    notes: ['Pimenta rosa', 'Rosa damascena', 'Almíscar'],
    description: 'Rosa damascena sobre pimenta rosa e almíscar. Intenso, feminino e memorável.',
    images: [IMAGES.rose],
  },
  {
    id: 'sabonete',
    name: 'Sabonetes Nesti Dante',
    price: 89,
    category: 'perfumaria',
    mood: 'Ritual de Banho',
    featured: false,
    sizes: ['Caixa com 2'],
    composition: '150g cada · sabonete artesanal italiano',
    notes: ['Chic Animalier', 'Immunity'],
    description: 'Dupla de sabonetes italianos: Chic Animalier (estampa animal) e Immunity (ervas revigorantes). Presente perfeito para o ritual de banho.',
    images: [IMAGES.candle],
  },
  {
    id: 'kit',
    name: 'Kit Presente Maison',
    price: 790,
    category: 'perfumaria',
    mood: 'Presente',
    featured: true,
    sizes: ['Único'],
    composition: '3 peças · caixa rígida forrada',
    description: 'Perfume Célli Nº1, vela Fico d\'Italia e sabonete artesanal em embalagem de presente com laço de cetim.',
    images: [IMAGES.gift],
  },
];

export const PILLARS = [
  {
    number: '01',
    title: 'Curadoria italiana',
    description: 'Perfumaria importada e tecidos escolhidos peça por peça, direto dos ateliês.',
  },
  {
    number: '02',
    title: 'Embalagem de presente',
    description: 'Toda compra chega pronta para presentear, com laço e cartão escrito à mão.',
  },
  {
    number: '03',
    title: 'Atendimento pessoal',
    description: 'Você fala com a gente pelo WhatsApp e monta o pedido com calma, sem carrinho frio.',
  },
];

export const LOOKBOOK_IMAGES = [
  IMAGES.editorial1,
  IMAGES.respira,
  IMAGES.bluelace,
  IMAGES.couple,
  IMAGES.editorial2,
  IMAGES.luxurygold,
  IMAGES.hearts,
  IMAGES.pinkbra,
  IMAGES.candle,
  IMAGES.mens,
];

export const GIFT_THRESHOLD = 790;
export const WHATSAPP_PHONE = '5519994727551';

export const formatPrice = (value) => {
  return value.toLocaleString('pt-BR', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
};

export const getWhatsAppLink = (message) => {
  return `https://wa.me/${WHATSAPP_PHONE}?text=${encodeURIComponent(message)}`;
};
